[package]
name = "cmdc"
version = "0.3.0"
edition = "2021"

[profile.release]
lto = "thin"
opt-level = 2
panic = "abort"

[dependencies]
clap = { version = "3.2.12", features = ["cargo"] }
encoding_rs = "0.8.33"
